### PR TITLE
auto-entities support

### PR DESCRIPTION
**Pull request by SBado**
A small patch to add support for [auto-entities](https://github.com/thomasloven/lovelace-auto-entities).

### CODE REVIEW

**Comment by daringer** [comment]
looks like it does not break anything, as predicted... Will play around with it the next days, especially because I've the plan to re-structure the docs/examples somewhere tomorrow. So if the examples also run fine, I would merge it to master ... 

maybe prepare yourself to add some example + documentation once I will provide the template for that, by tomorrow hopefully

**Comment by daringer** [comment]
Presenting the new [docs](https://github.com/custom-cards/flex-table-card/tree/master/docs). Still found no issues, while testing your patch, perfect. 

Could you assemble a small example (include the auto-entites portion please), write two lines, link auto-entities, simply use [this template](https://github.com/custom-cards/flex-table-card/blob/master/docs/_example-cfg-template.md)

**Comment by SBado** [comment]
Done, let me know if the document is ok.

**Comment by daringer** [comment]
very nice! two picky details:
* typo in filename: `example-cfg-autoentioties.md` 
* please add a link to the example into the top-level README.md

**Comment by SBado** [comment]
Sorry! Typo fixed and link added.

**Comment by daringer** [comment]
perfect, thanks

**Pull request merged**
